import type { GraphEdge, GraphNode } from "@/lib/patchbay/types";

const up = "up" as const;

function n(
  partial: Pick<GraphNode, "id" | "label" | "kind" | "x" | "y"> &
    Partial<Omit<GraphNode, "id" | "label" | "kind" | "x" | "y">>,
): GraphNode {
  return {
    ip: "",
    mac: "",
    vlan: "",
    os: "",
    status: "unknown",
    notes: "",
    ports: [],
    tags: [],
    pinned: false,
    ...partial,
  };
}

export const SAMPLE_NAME = "North rack";

export const SAMPLE_NODES: GraphNode[] = [
  n({
    id: "internet",
    label: "WAN",
    kind: "network",
    x: -680,
    y: -30,
    notes: "Upstream. The lab does not own this hop.",
    tags: ["edge"],
    status: up,
  }),
  n({
    id: "opnsense",
    label: "OPNsense",
    kind: "router",
    ip: "10.0.0.1",
    mac: "bc:24:11:6a:10:01",
    os: "OPNsense 25.1",
    vlan: "trunk",
    status: up,
    ports: ["22", "443", "8443"],
    tags: ["edge", "firewall"],
    x: -440,
    y: -30,
    notes: "Edge firewall. WAN on igb0, trunk toward the core on igb1. Unbound is the recursor.",
  }),
  n({
    id: "crs",
    label: "CRS310",
    kind: "switch",
    ip: "10.0.0.2",
    mac: "48:a9:8a:11:00:02",
    os: "RouterOS 7.18",
    status: up,
    ports: ["22", "80", "8291"],
    tags: ["core"],
    x: -180,
    y: 0,
    notes: "Core switch. VLANs 10, 20, 30, and 40. Two 2.5GbE drops to the access points.",
  }),
  n({
    id: "ap-living",
    label: "AP living",
    kind: "ap",
    ip: "10.0.0.11",
    os: "UniFi",
    status: up,
    ports: ["22", "8080"],
    tags: ["wifi"],
    x: -180,
    y: -210,
    notes: "Ceiling AP. Home SSID on VLAN 10, guest SSID on VLAN 40.",
  }),
  n({
    id: "ap-office",
    label: "AP office",
    kind: "ap",
    ip: "10.0.0.12",
    os: "UniFi",
    status: up,
    ports: ["22", "8080"],
    tags: ["wifi"],
    x: -180,
    y: 220,
    notes: "Desk-side AP. Workstation associates here.",
  }),
  n({
    id: "vlan-lan",
    label: "LAN",
    kind: "network",
    ip: "10.0.10.0/24",
    vlan: "10",
    status: up,
    tags: ["vlan"],
    x: 80,
    y: -250,
    notes: "Trusted clients. DHCP from OPNsense.",
  }),
  n({
    id: "vlan-srv",
    label: "Servers",
    kind: "network",
    ip: "10.0.20.0/24",
    vlan: "20",
    status: up,
    tags: ["vlan"],
    x: 90,
    y: -10,
    notes: "Hypervisor, NAS, and internal services.",
  }),
  n({
    id: "vlan-iot",
    label: "IoT",
    kind: "network",
    ip: "10.0.30.0/24",
    vlan: "30",
    status: up,
    tags: ["vlan"],
    x: 80,
    y: 210,
    notes: "No east-west to LAN. Cameras and plugs only.",
  }),
  n({
    id: "vlan-guest",
    label: "Guest",
    kind: "network",
    ip: "10.0.40.0/24",
    vlan: "40",
    status: up,
    tags: ["vlan"],
    x: 80,
    y: 400,
    notes: "Client isolation. Internet only.",
  }),
  n({
    id: "printer",
    label: "Printer",
    kind: "iot",
    ip: "10.0.10.50",
    status: up,
    ports: ["9100", "631"],
    tags: ["lan"],
    x: 340,
    y: -310,
    notes: "IPP on the trusted VLAN.",
  }),
  n({
    id: "workstation",
    label: "Workstation",
    kind: "host",
    ip: "10.0.10.40",
    os: "macOS",
    status: up,
    tags: ["lan"],
    x: 360,
    y: -170,
    notes: "Daily driver. Associates to the office AP.",
  }),
  n({
    id: "pve",
    label: "pve-01",
    kind: "host",
    ip: "10.0.20.10",
    mac: "bc:24:11:6a:20:10",
    os: "Proxmox VE 8.4",
    vlan: "20",
    status: up,
    ports: ["22", "8006"],
    tags: ["compute"],
    x: 380,
    y: -20,
    notes: "Single node. Guests bridge vmbr0 onto VLAN 20.",
  }),
  n({
    id: "nas",
    label: "TrueNAS",
    kind: "storage",
    ip: "10.0.20.20",
    mac: "00:11:32:2a:20:20",
    os: "TrueNAS SCALE",
    vlan: "20",
    status: up,
    ports: ["22", "445", "2049"],
    tags: ["storage"],
    x: 380,
    y: 180,
    notes: "Mirror tank. NFS for Immich, nightly backup target for Home Assistant. NUT client.",
  }),
  n({
    id: "ups",
    label: "Back-UPS",
    kind: "ups",
    ip: "10.0.0.5",
    os: "NUT",
    status: up,
    ports: ["3493"],
    tags: ["power"],
    x: -440,
    y: 180,
    notes: "Rack UPS. Notifies pve-01 and TrueNAS over NUT.",
  }),
  n({
    id: "cam",
    label: "Driveway cam",
    kind: "iot",
    ip: "10.0.30.21",
    status: "down",
    ports: ["554", "80"],
    tags: ["iot"],
    x: 360,
    y: 330,
    notes: "No ICMP since yesterday. The PoE port still draws.",
  }),
  n({
    id: "plug",
    label: "Shelly plug",
    kind: "iot",
    ip: "10.0.30.22",
    os: "Shelly",
    status: up,
    ports: ["80"],
    tags: ["iot"],
    x: 540,
    y: 400,
    notes: "Printer-side plug, on the IoT VLAN.",
  }),
  n({
    id: "caddy",
    label: "Caddy",
    kind: "proxy",
    ip: "10.0.20.30",
    os: "Debian",
    vlan: "20",
    status: up,
    ports: ["80", "443"],
    tags: ["edge", "vm"],
    x: 660,
    y: -200,
    notes: "Internal HTTPS for *.home. Certificates from the LAN CA.",
  }),
  n({
    id: "unbound",
    label: "Unbound",
    kind: "dns",
    ip: "10.0.20.53",
    os: "Debian",
    vlan: "20",
    status: up,
    ports: ["53"],
    tags: ["dns", "lxc"],
    x: 660,
    y: -70,
    notes: "Recursive resolver. OPNsense forwards LAN queries here.",
  }),
  n({
    id: "ha",
    label: "Home Assistant",
    kind: "vm",
    ip: "10.0.20.40",
    os: "HAOS",
    vlan: "20",
    status: up,
    ports: ["8123"],
    tags: ["vm"],
    x: 660,
    y: 50,
    notes: "Automations. Talks to IoT through the firewall, not directly.",
  }),
  n({
    id: "immich",
    label: "Immich",
    kind: "container",
    ip: "10.0.20.41",
    os: "LXC",
    vlan: "20",
    status: up,
    ports: ["2283"],
    tags: ["lxc"],
    x: 860,
    y: 50,
    notes: "Photo library. Library path is an NFS mount from TrueNAS.",
  }),
  n({
    id: "grafana",
    label: "Grafana",
    kind: "service",
    ip: "10.0.20.42",
    os: "Debian",
    vlan: "20",
    status: up,
    ports: ["3000"],
    tags: ["lxc"],
    x: 660,
    y: 190,
    notes: "Dashboards for node exporter, NUT, and switch SNMP.",
  }),
  n({
    id: "forgejo",
    label: "Forgejo",
    kind: "service",
    ip: "10.0.20.43",
    os: "Debian",
    vlan: "20",
    status: up,
    ports: ["3000", "22"],
    tags: ["lxc", "git"],
    x: 860,
    y: 190,
    notes: "Git remote for this lab's manifests.",
  }),
];

export const SAMPLE_EDGES: GraphEdge[] = [
  { id: "e1", source: "internet", target: "opnsense", label: "PPPoE" },
  { id: "e2", source: "opnsense", target: "crs", label: "igb1" },
  { id: "e3", source: "crs", target: "ap-living", label: "2.5GbE" },
  { id: "e4", source: "crs", target: "ap-office", label: "2.5GbE" },
  { id: "e5", source: "crs", target: "vlan-lan", label: "VLAN 10" },
  { id: "e6", source: "crs", target: "vlan-srv", label: "VLAN 20" },
  { id: "e7", source: "crs", target: "vlan-iot", label: "VLAN 30" },
  { id: "e8", source: "crs", target: "vlan-guest", label: "VLAN 40" },
  { id: "e9", source: "ap-living", target: "vlan-guest", label: "SSID guest" },
  { id: "e10", source: "ap-office", target: "workstation", label: "Wi-Fi 6" },
  { id: "e11", source: "vlan-lan", target: "printer", label: "access" },
  { id: "e12", source: "vlan-lan", target: "workstation", label: "access" },
  { id: "e13", source: "vlan-srv", target: "pve", label: "vmbr0" },
  { id: "e14", source: "vlan-srv", target: "nas", label: "10GbE" },
  { id: "e15", source: "pve", target: "caddy", label: "vm 101" },
  { id: "e16", source: "pve", target: "unbound", label: "lxc 102" },
  { id: "e17", source: "pve", target: "ha", label: "vm 103" },
  { id: "e18", source: "pve", target: "immich", label: "lxc 104" },
  { id: "e19", source: "pve", target: "grafana", label: "lxc 105" },
  { id: "e20", source: "pve", target: "forgejo", label: "lxc 106" },
  { id: "e21", source: "nas", target: "immich", label: "nfs" },
  { id: "e22", source: "nas", target: "ha", label: "backup" },
  { id: "e23", source: "caddy", target: "ha", label: "ha.home" },
  { id: "e24", source: "caddy", target: "immich", label: "photos.home" },
  { id: "e25", source: "caddy", target: "grafana", label: "graf.home" },
  { id: "e26", source: "caddy", target: "forgejo", label: "git.home" },
  { id: "e27", source: "opnsense", target: "unbound", label: "recursor" },
  { id: "e28", source: "vlan-iot", target: "cam", label: "access" },
  { id: "e29", source: "vlan-iot", target: "plug", label: "access" },
  { id: "e30", source: "ups", target: "pve", label: "NUT" },
  { id: "e31", source: "ups", target: "nas", label: "NUT" },
];

export type ScanBeat = { log: string; nodeIds: string[]; edgeIds: string[] };

export const SCAN_BEATS: ScanBeat[] = [
  {
    log: "Gateway 10.0.0.1 answers on 443 and 22. LLDP names it OPNsense.",
    nodeIds: ["internet", "opnsense"],
    edgeIds: ["e1"],
  },
  {
    log: "igb1 neighbor is CRS310 at 10.0.0.2. Trunk carries VLANs 10, 20, 30, 40.",
    nodeIds: ["crs", "vlan-lan", "vlan-srv", "vlan-iot", "vlan-guest"],
    edgeIds: ["e2", "e5", "e6", "e7", "e8"],
  },
  {
    log: "Access points 10.0.0.11 and 10.0.0.12 up on 2.5GbE. Guest SSID bound to VLAN 40.",
    nodeIds: ["ap-living", "ap-office"],
    edgeIds: ["e3", "e4", "e9"],
  },
  {
    log: "LAN clients: workstation 10.0.10.40, printer 10.0.10.50.",
    nodeIds: ["workstation", "printer"],
    edgeIds: ["e10", "e11", "e12"],
  },
  {
    log: "Server VLAN: pve-01 on 8006, TrueNAS on 445 and 2049.",
    nodeIds: ["pve", "nas"],
    edgeIds: ["e13", "e14"],
  },
  {
    log: "Guests on pve-01: Caddy, Unbound, Home Assistant, Immich, Grafana, Forgejo.",
    nodeIds: ["caddy", "unbound", "ha", "immich", "grafana", "forgejo"],
    edgeIds: ["e15", "e16", "e17", "e18", "e19", "e20", "e27"],
  },
  {
    log: "Caddy certificates match ha.home, photos.home, graf.home, git.home. NFS from the NAS.",
    nodeIds: [],
    edgeIds: ["e21", "e22", "e23", "e24", "e25", "e26"],
  },
  {
    log: "IoT VLAN: Shelly answers. Driveway cam is silent on ICMP. NUT sees the rack UPS.",
    nodeIds: ["cam", "plug", "ups"],
    edgeIds: ["e28", "e29", "e30", "e31"],
  },
];
